### ISSUE TITLE
help:/

### ISSUE THREAD

**Issue by amirwolf5122** [CoolCoderSJ/replit-oauth#3]
https://replit-oauth.coolcodersj.repl.co/api/v1
Does not work

**Comment by CoolCoderSJ** [comment]
What doesn't work? Can you send the specific route you tried using?

**Comment by amirwolf5122** [comment]
import requests
token = "l4k75fth031bcmxbkny28owj5sf9xnca50kb7rybnb3js5vr0j660zcqv8stkqr8dwarg3m56ww417ib0owgsurqv1j7e8nn6crb"
api = "https://replit-oauth.coolcodersj.repl.co/api/v1"
user_id= requests.post(f"{api}/me/id", headers={
    "Authorization": f"Bearer {token}"
})
user_id = user_id.text
print(user_id)

error
"
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your requ
est. Either the server is overloaded or there is an error in the application.</p
>
"

**Comment by CoolCoderSJ** [comment]
I'll take a look into it.

**Comment by amirwolf5122** [comment]
Hello, don't worry, I fixed the problem, thank you
